// Auto-generated by scripts/translations.js
// Do not edit this file manually.
// All changes will be overwritten.

export const translations: Record<string, { [key: string]: string }> = {
  "en": {},
  "es": {},
  "it": {},
  "fr": {},
  "de": {},
  "nl": {}
};
