;-D DEV_IP_OVERRIDE_STA_IP=${sysenv.DEV_IP_OVERRIDE_STA_IP}

[common]
;extra_scripts = scripts/LittleFSBuilder.py
extra_scripts = scripts/strip_elf.py
lib_ignore = WebServer
upload_protocol = esptool
debug_init_break = tbreak setup
monitor_filters = esp32_exception_decoder
board_upload.speed = 115200
board_build.mcu = esp32s3
board_build.variant = esp32s3
board_build.filesystem = littlefs

[env:waveshare_base]
extends = common
debug_tool = esp-builtin
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_filters = esp32_exception_decoder
board_build.flash_mode = dio
board_build.prsam_type = opi
build_flags =
	-std=gnu++17
	-I src
	-I lib/polymech-base/src
board_build.extra_flags = 
	-DBOARD_HAS_PSRAM
	-DARDUINO_ESP32S3_DEV
	-DARDUINO_USB_MODE=1
	-DWS_MAX_QUEUED_MESSAGES=64
	-DWS_SEND_QUEUE_SIZE=64
	-DWS_MIN_SEND_INTERVAL_MS=10
	-DPROJECT_DIR="\"${PROJECT_DIR}\""
lib_deps = 
	https://github.com/eModbus/eModbus.git
	https://github.com/janelia-arduino/Vector.git
	https://github.com/thijse/Arduino-Log.git
	https://github.com/bblanchon/ArduinoJson.git
	https://github.com/ESP32Async/ESPAsyncWebServer.git

[env:waveshare]
monitor_filters = esp32_exception_decoder
extends = env:waveshare_base
lib_deps = 
	${env:waveshare_base.lib_deps}
board_build.extra_flags = 
	${env:waveshare_base.board_build.extra_flags}
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DLOG_LEVEL=LOG_LEVEL_INFO
	-DENABLE_LOGGING
	-DWS_MAX_QUEUED_MESSAGES=16
	-DWS_SEND_QUEUE_SIZE=16
	-DWS_MIN_SEND_INTERVAL_MS=80

[env:waveshare-release]
monitor_filters = esp32_exception_decoder
build_type = release
extends = env:waveshare_base
board_build.extra_flags = 
  ${env:waveshare_base.board_build.extra_flags}
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DLOG_LEVEL=0
  -DDISABLE_LOGGING
  -DPIO_DISABLE_LOGGER
  -DCONFIG_LOG_DEFAULT_LEVEL=0
  -DCONFIG_LOG_MAXIMUM_LEVEL=0
  -DLOG_LOCAL_LEVEL=0
  -Wl,--gc-sections
lib_ignore = WebServer
lib_deps = 
	${env:waveshare_base.lib_deps}

[env:waveshare-release-debug]
monitor_filters = esp32_exception_decoder
build_type = release
extends = env:waveshare_base
board_build.extra_flags = 
  ${env:waveshare_base.board_build.extra_flags}
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DLOG_LEVEL=LOG_LEVEL_INFO
  -DENABLE_LOGGING
  -Wl,--gc-sections
lib_ignore = WebServer
lib_deps = 
	${env:waveshare_base.lib_deps}
