#ifndef CONFIG_USER_H
#define CONFIG_USER_H

//#define ENABLE_OMRON_E5
#define NUM_OMRON_DEVICES 0
//#define ENABLE_AMPERAGE_BUDGET_MANAGER
//#define ENABLE_JOYSTICK

//#define ENABLE_PROFILE_TEMPERATURE
//#define ENABLE_PROFILE_SIGNAL_PLOT
//#define ENABLE_PROFILE_PRESSURE

#define PROFILE_PRESSURE_COUNT 0
#define PROFILE_TEMPERATURE_COUNT 2
#define PROFILE_SIGNAL_PLOT_COUNT 2

//#define ENABLE_PRESS_CYLINDER
//#define ENABLE_LOADCELL_0
//##define ENABLE_LOADCELL_1
//#define ENABLE_SOLENOID_0
//#define ENABLE_SOLENOID_1
//#define ENABLE_FEEDBACK_BUZZER
//#define ENABLE_FEEDBACK_3C
//#define ENABLE_OPERATOR_SWITCH
#define ENABLE_POT0
#define ENABLE_POT1

#undef ENABLE_SAKO_VFD
#undef ENABLE_DELTA_VFD
#undef ENABLE_PLUNGER

#define ENABLE_MB_GPIO
#define MB_GPIO_OP_INTERVAL_MS 50
#define MB_GPIO_DEFAULT_TYPE E_GPIO_TYPE_INPUT
#define MB_GPIO_ALL_ESP32_PINS
#define MB_GPIO_BASE_ADDR 300

#undef HMI_NAME
#define HMI_NAME "Tanit IO"


#endif // CONFIG_USER_H
