#ifndef CONFIG_OVERRIDE_H
#define CONFIG_OVERRIDE_H

#undef ENABLE_RS485
#undef ENABLE_RS485_DEVICES

#undef ENABLE_SETTINGS
#undef ENABLE_RUNTIME_STATE

#undef ENABLE_LOGGER
#undef ENABLE_SERIAL_BRIDGE
#undef REST_SERVER_APP_ROUTES

#define DISABLE_SERIAL_LOGGING

// #undef ENABLE_REST_SERVER
// #undef ENABLE_LITTLEFS
//#undef ENABLE_WEBSOCKET

#endif