#ifndef CONFIG_USER_H
#define CONFIG_USER_H
/*
#undef ENABLE_AMPERAGE_BUDGET_MANAGER
#define ENABLE_FEEDBACK_BUZZER
#define ENABLE_FEEDBACK_3C
#define ENABLE_LOADCELL_0
#define ENABLE_LOADCELL_1
#define ENABLE_SOLENOID_0
#define ENABLE_SOLENOID_1

#define ENABLE_PRESS_CYLINDER
#define ENABLE_OMRON_E5
#define ENABLE_JOYSTICK
#define ENABLE_AMPERAGE_BUDGET_MANAGER
#define ENABLE_OPERATOR_SWITCH
#define ENABLE_PROFILE_TEMPERATURE
#define ENABLE_PROFILE_PRESSURE
#define ENABLE_PROFILE_SIGNAL_PLOT
#define ENABLE_PROFILE_PRESSURE
*/
/*
#define NUM_OMRON_DEVICES 0
#define PROFILE_PRESSURE_COUNT 0
#define PROFILE_TEMPERATURE_COUNT 0
#define PROFILE_SIGNAL_PLOT_COUNT 0
#define ENABLE_HY_VFD
#define ENABLE_SAKO_VFD
#define ENABLE_POT0
#define ENABLE_PLUNGER
#define ENABLE_DELTA_VFD
#define ENABLE_POT1
*/
// Cassandra config - minimum
#define ENABLE_OMRON_E5
#define NUM_OMRON_DEVICES 8

#define ENABLE_AMPERAGE_BUDGET_MANAGER
#define ENABLE_JOYSTICK

#define ENABLE_PROFILE_TEMPERATURE
#define ENABLE_PROFILE_SIGNAL_PLOT
#define ENABLE_PROFILE_PRESSURE

#define PROFILE_PRESSURE_COUNT 1
#define PROFILE_TEMPERATURE_COUNT 4
#define PROFILE_SIGNAL_PLOT_COUNT 4

#define ENABLE_PRESS_CYLINDER
#define ENABLE_LOADCELL_0
#define ENABLE_LOADCELL_1
#define ENABLE_SOLENOID_0
#define ENABLE_SOLENOID_1
#define ENABLE_FEEDBACK_BUZZER
#define ENABLE_FEEDBACK_3C
#define ENABLE_OPERATOR_SWITCH

#endif // CONFIG_USER_H