; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_scripts = scripts/LittleFSBuilder.py

; -DDISABLE_SERIAL_LOGGING
; -DDEBUG_APP_STATE


[env:waveshare]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
extra_scripts = scripts/LittleFSBuilder.py
board_build.filesystem = littlefs
board_build.arduino.ldscript = esp32s3_out.ld
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.prsam_type = opi
board_build.mcu = esp32s3
board_build.variant = esp32s3
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_upload.speed = 921600
build_flags =
	-std=gnu++17
	-I src
	-I lib/polymech-base/src
board_build.extra_flags = 
	-DBOARD_HAS_PSRAM
	-DARDUINO_ESP32S3_DEV
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DLOG_LEVEL=LOG_LEVEL_INFO
lib_ignore = WebServer
lib_deps = 
	https://github.com/plerup/espsoftwareserial.git
	https://github.com/eModbus/eModbus.git
	https://github.com/janelia-arduino/Vector.git
	https://github.com/thijse/Arduino-Log.git
	https://github.com/bblanchon/ArduinoJson.git
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	https://github.com/me-no-dev/AsyncTCP.git
debug_tool = esp-builtin
upload_protocol = esptool
debug_init_break = tbreak setup
monitor_filters = esp32_exception_decoder

[env:waveshare-release]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
extra_scripts = scripts/LittleFSBuilder.py
board_build.filesystem = littlefs
board_build.arduino.ldscript = esp32s3_oleasut.ld
board_build.partitions = custom_partitions.csv
board_build.arduino.memory_type = qio_opi
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.prsam_type = opi
board_build.mcu = esp32s3
board_build.variant = esp32s3
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_upload.speed = 921600
build_flags =
	-std=gnu++17
	-I src
	-I lib/polymech-base/src
board_build.extra_flags = 
	-DBOARD_HAS_PSRAM
	-DARDUINO_ESP32S3_DEV
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DLOG_LEVEL=0	
	-DDISABLE_LOGGING
lib_ignore = WebServer
lib_deps = 
	https://github.com/plerup/espsoftwareserial.git
	https://github.com/eModbus/eModbus.git
	https://github.com/janelia-arduino/Vector.git
	https://github.com/thijse/Arduino-Log.git
	https://github.com/bblanchon/ArduinoJson.git
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	https://github.com/me-no-dev/AsyncTCP.git
debug_tool = esp-builtin
upload_protocol = esptool
debug_init_break = tbreak setup
monitor_filters = esp32_exception_decoder
