/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#ifdef ENABLE_WEBSOCKET_PB
#include "proto/registers.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Register, Register, AUTO)


PB_BIND(RegistersResponseMetadata, RegistersResponseMetadata, AUTO)


PB_BIND(RegistersResponse, RegistersResponse, AUTO)


#endif