#pragma once

// Sako Parameter Group Communication Access Addresses (from manual):
// P0 ~ PE Group: 0xF000 - 0xFEFF
// A0 ~ AC Group: 0xA000 - 0xACFF
// U0 Group (Monitoring): 0x7000 - 0x70FF

enum class E_SAKO_STATUS : int 
{
    E_SAKO_STATUS_DIRECTION = 0x3000    
};
enum class E_SAKO_REGISTERS   : int 
{
    E_SAKO_REGISTERS_SET_DIR = 0x2000,
    E_SAKO_REGISTERS_ERROR = 0x8000
};
enum class E_SAKO_DIRECTION : int 
{
    E_SAKO_DIR_FWD = 1,
    E_SAKO_DIR_REV = 2,
    E_SAKO_DIR_JOGGING = 3,
    E_SAKO_DIR_REVERSE_JOGGING = 4,
    E_SAKO_DIR_FREE_STOP = 5,
    E_SAKO_DIR_DECELERATION_STOP = 6,
    E_SAKO_DIR_FAULT_RESET = 7
};

enum class E_SAKO_MON : int {
    E_SAKO_MON_RUNNING_FREQUENCY_HZ = 0x7000, // U0-00 Running frequency (Hz)
    E_SAKO_MON_SET_FREQUENCY_HZ, // U0-01 Set frequency (Hz)
    E_SAKO_MON_BUS_VOLTAGE_V, // U0-02 Bus voltage (V)
    E_SAKO_MON_OUTPUT_VOLTAGE_V, // U0-03 Output voltage (V)
    E_SAKO_MON_OUTPUT_CURRENT_A, // U0-04 Output current (A)
    E_SAKO_MON_OUTPUT_POWER_KW, // U0-05 Output power (kW)
    E_SAKO_MON_OUTPUT_TORQUE_PERCENT, // U0-06 Output torque (%)
    E_SAKO_MON_DI_INPUT_STATE, // U0-07 DI input state
    E_SAKO_MON_DO_OUTPUT_STATE, // U0-08 DO output state
    E_SAKO_MON_AI1_VOLTAGE_V, // U0-09 AI1 voltage (V)
    E_SAKO_MON_AI2_VOLTAGE_V_CURRENT_MA, // U0-10 AI2 voltage (V)/current (mA)
    E_SAKO_MON_PANEL_POTENTIOMETER_VOLTAGE_V, // U0-11 Panel potentiometer voltage (V)
    E_SAKO_MON_COUNT_VALUE, // U0-12 Count value
    E_SAKO_MON_LENGTH_VALUE, // U0-13 Length value
    E_SAKO_MON_LOAD_SPEED_DISPLAY, // U0-14 Load speed display
    E_SAKO_MON_PID_SETTING, // U0-15 PID setting
    E_SAKO_MON_PID_FEEDBACK, // U0-16 PID feedback
    E_SAKO_MON_PLC_STAGE, // U0-17 PLC stage
    E_SAKO_MON_HDI_INPUT_PULSE_FREQUENCY_HZ, // U0-18 HDI input pulse frequency (Hz)
    E_SAKO_MON_FEEDBACK_SPEED_HZ, // U0-19 Feedback speed (Hz)
    E_SAKO_MON_REMAINING_RUNNING_TIME, // U0-20 Remaining running time
    E_SAKO_MON_AI1_VOLTAGE_BEFORE_CORRECTION, // U0-21 AI1 voltage before correction
    E_SAKO_MON_AI2_VOLTAGE_V_CURRENT_MA_BEFORE_CORRECTION, // U0-22 AI2 voltage (V)/current (mA) before correction
    E_SAKO_MON_PANEL_POTENTIOMETER_VOLTAGE_BEFORE_CORRECTION, // U0-23 Panel potentiometer voltage before correction
    E_SAKO_MON_LINEAR_SPEED, // U0-24 Linear speed
    E_SAKO_MON_ACCUMULATIVE_POWER_ON_TIME, // U0-25 Accumulative power-on time
    E_SAKO_MON_ACCUMULATIVE_RUNNING_TIME, // U0-26 Accumulative running time
    E_SAKO_MON_HDI_PULSE_INPUT_FREQUENCY, // U0-27 HDI pulse input frequency
    E_SAKO_MON_COMMUNICATION_SETTING_VALUE, // U0-28 Communication setting value

    E_SAKO_MON_MAIN_FREQUENCY_X = 1030, // U0-30 Main frequency X
    E_SAKO_MON_AUXILIARY_FREQUENCY_Y, // U0-31 Auxiliary frequency Y
    E_SAKO_MON_VIEWING_ANY_REGISTER_ADDRESS_VALUE, // U0-32 Viewing any register address value

    E_SAKO_MON_TARGET_TORQUE_PERCENT = 1035, // U0-35 Target torque (%)
    E_SAKO_MON_ROTATION_POSITION, // U0-36 Rotation position
    E_SAKO_MON_POWER_FACTOR_ANGLE, // U0-37 Power factor angle

    E_SAKO_MON_TARGET_VOLTAGE_UPON_VF_SEPARATION = 1039, // U0-39 Target voltage upon V/F separation
    E_SAKO_MON_OUTPUT_VOLTAGE_UPON_VF_SEPARATION, // U0-40 Output voltage upon V/F separation
    E_SAKO_MON_DI_STATE_VISUAL_DISPLAY, // U0-41 DI state visual display
    E_SAKO_MON_DO_STATE_VISUAL_DISPLAY, // U0-42 DO state visual display
    E_SAKO_MON_DI_FUNCTION_STATE_VISUAL_DISPLAY_1_FUNCTION_01_40, // U0-43 DI function state visual display 1 (function 01-40)
    E_SAKO_MON_DI_FUNCTION_STATE_VISUAL_DISPLAY_2_FUNCTION_41_80, // U0-44 DI function state visual display 2 (function 41-80)
    E_SAKO_MON_FAULT_INFORMATION, // U0-45 Fault information

    E_SAKO_MON_CURRENT_SET_FREQUENCY_PERCENT = 1059, // U0-59 Current set frequency(%)
    E_SAKO_MON_CURRENT_RUNNING_FREQUENCY_PERCENT, // U0-60 Current running frequency(%)
    E_SAKO_MON_AC_DRIVE_RUNNING_STATE, // U0-61 AC drive running state
    E_SAKO_MON_CURRENT_FAULT_CODE, // U0-62 Current fault code

    E_SAKO_MON_TORQUE_UPPER_LIMIT = 1065, // U0-65 Torque upper limit
};

enum class E_SAKO_ERROR : int {
    E_SAKO_ERROR_NO_FAULT = 0,
    E_SAKO_ERROR_OVERCURRENT = 2,
    E_SAKO_ERROR_OVERCURRENT_ACCEL = 3,
    E_SAKO_ERROR_OVERCURRENT_DECEL = 4,
    E_SAKO_ERROR_OVERVOLTAGE_CONST = 5,
    E_SAKO_ERROR_OVERVOLTAGE_ACCEL = 6,
    E_SAKO_ERROR_OVERVOLTAGE_DECEL = 7,
    E_SAKO_ERROR_BUFFER_RESISTANCE_OVERLOAD = 8,
    E_SAKO_ERROR_UNDERVOLTAGE = 9,
    E_SAKO_ERROR_FREQUENCY_CONVERTER_OVERLOAD = 10, // 0x0A
    E_SAKO_ERROR_MOTOR_OVERLOAD = 11, // 0x0B
    E_SAKO_ERROR_INPUT_LACK_PHASE = 12, // 0x0C
    E_SAKO_ERROR_OUTPUT_LACK_PHASE = 13, // 0x0D
    E_SAKO_ERROR_MODULE_OVERHEATING = 14, // 0x0E
    E_SAKO_ERROR_EXTERNAL_FAULT = 15, // 0x0F
    E_SAKO_ERROR_COMMUNICATION_ABNORMAL = 16, // 0x10
    E_SAKO_ERROR_CONTACTOR_ABNORMAL = 17, // 0x11
    E_SAKO_ERROR_CURRENT_DETECTION = 18, // 0x12
    E_SAKO_ERROR_MOTOR_TUNING = 19, // 0x13
    E_SAKO_ERROR_ENCODER_PG_CARD_FAILURE = 20, // 0x14
    E_SAKO_ERROR_PARAMETER_RW_ABNORMAL = 21, // 0x15 - Corrected value
    E_SAKO_ERROR_HARDWARE = 22, // 0x16
    E_SAKO_ERROR_MOTOR_SHORT_CIRCUIT_GROUND = 23, // 0x17
    E_SAKO_ERROR_RUN_TIME_UP = 26, // 0x1A
    E_SAKO_ERROR_USER_CUSTOM_1 = 27, // 0x1B
    E_SAKO_ERROR_USER_CUSTOM_2 = 28, // 0x1C
    E_SAKO_ERROR_POWER_ON_TIME_UP = 29, // 0x1D
    E_SAKO_ERROR_OFF_LOAD = 30, // 0x1E
    E_SAKO_ERROR_LOSS_OF_PID_FEEDBACK = 31, // 0x1F
    E_SAKO_ERROR_FAST_CURRENT_LIMIT_TIMEOUT = 40, // 0x28
    E_SAKO_ERROR_SWITCHING_MOTOR_FAULT = 41, // 0x29
    E_SAKO_ERROR_SPEED_DEVIATION_TOO_LARGE = 42, // 0x2A
    E_SAKO_ERROR_MOTOR_OVERSPEED = 43, // 0x2B
    E_SAKO_ERROR_MOTOR_OVERTEMPERATURE = 45, // 0x2D
    E_SAKO_ERROR_ENCODER_LINE_NUMBER_SETTING = 90, // 0x5A
    E_SAKO_ERROR_ENCODER_UNCONNECTED = 91, // 0x5B
    E_SAKO_ERROR_INITIAL_POSITION = 92, // 0x5C
    E_SAKO_ERROR_SPEED_FEEDBACK = 94, // 0x5E
};